apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: wikipedia-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikipedia
  template:
    metadata:
      labels:
        app: wikipedia
    spec:
      volumes:
        - name: www
          emptyDir: {}
      initContainers:
        - name: wikipedia-fetcher
          image: curlimages/curl:8.11.1
          command:
            - sh
            - -c
            - curl -sL https://en.wikipedia.org/wiki/Kubernetes -o /usr/share/nginx/html/index.html
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
        - name: wikipedia-randomizer
          image: curlimages/curl:8.11.1
          restartPolicy: Always
          command:
            - sh
            - -c
            - |
              while true; do
                sleep $(awk 'BEGIN { srand(); print int(300 + rand() * 601) }')
                curl -sL https://en.wikipedia.org/wiki/Special:Random -o /usr/share/nginx/html/index.html
              done
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      containers:
        - name: wikipedia
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
