apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: wikipedia-svc
spec:
  type: ClusterIP
  selector:
    app: wikipedia
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 80
