apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: todo-app:1.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: project-configmap
