apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: project-configmap
data:
  PORT: "3000"
  TODO_BACKEND_URL: http://todo-backend-svc:2345
  IMAGE_URL: https://picsum.photos/1200
  IMAGE_DIR: /usr/src/app/files
  IMAGE_CACHE_MINUTES: "10"
  TODO_MAX_LENGTH: "140"
