apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim
spec:
  storageClassName: shared-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
spec:
  storageClassName: image-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
