apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: log-output-writer:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: log-output-reader:1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: http://ping-pong-svc:2346
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
