name: Release the project to staging

on:
  push:
    branches:
      - main

jobs:
  build-publish-release:
    name: Build, Publish and Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to the container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        env:
          REGISTRY: ghcr.io/rororo06
        run: |-
          for app in todo-app todo-backend broadcaster; do
            docker build --tag "$REGISTRY/$app:$GITHUB_SHA" $app
            docker push "$REGISTRY/$app:$GITHUB_SHA"
          done

      - name: Checkout the configuration repository
        uses: actions/checkout@v6
        with:
          repository: Rororo06/devops-config
          token: ${{ secrets.CONFIG_REPO_TOKEN }}
          path: config

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Use the new images
        working-directory: config/overlays/staging
        env:
          REGISTRY: ghcr.io/rororo06
        run: |-
          kustomize edit set image PROJECT/TODO_APP=$REGISTRY/todo-app:$GITHUB_SHA
          kustomize edit set image PROJECT/TODO_BACKEND=$REGISTRY/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/BROADCASTER=$REGISTRY/broadcaster:$GITHUB_SHA

      - name: Commit the new images to the configuration repository
        uses: EndBug/add-and-commit@v10
        with:
          cwd: config
          add: overlays/staging/kustomization.yaml
          message: New staging version released ${{ github.sha }}
